import Head from "next/head";
import Header from "@/components/Header";
import styles from "@/styles/Layout.module.sass";
import type { LayoutProps } from "@/types";

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>The Good Corner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles["main-content"]}>{children}</main>
    </>
  );
}
